# This is a basic workflow to help you get started with Actions

name: CI
on: push

jobs:
  ts_project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts_project
    steps:
      - uses: actions/checkout@v2
      - name: Setup bazel
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        

  typescript_docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript_docker
    steps:
      - uses: actions/checkout@v2
      - name: Setup bazel
        run: yarn install
        
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
    
